### ISSUE TITLE
Adding Dockerfile to main repo

### ISSUE THREAD

**Issue by stepman0** [murmeltier08/Sonos-Kids-Controller#3]
Just an idea, how about adding the Dockerfile to Thyraz's main repo? Than the Dockerfile keeps up to date with the source code...

Assumed that this is ok for both you and Thyraz

**Comment by murmeltier08** [comment]
This was also in my mind. We can ask him. I should by able to pull the image to docker hub. What is the workflow ? I think Thyraz do not use docker
